### ISSUE TITLE
Issue with regular expression

### ISSUE THREAD

**Issue by lukeclifton** [kotyy/craft-password-enforcer#2]
Installed the plugin and tested but when i was trying a password which did satisfy all the the default requirements, the validation still failed.

The error `Your password must contain letters, numbers and symbols.` kept showing.

I think there may be an issue with the regular expression or something?

When i tried this expression it worked fine:
`$\S*(?=\S{8,})(?=\S*[a-z])(?=\S*[A-Z])(?=\S*[\d])(?=\S*[\W])\S*$`

Explaining $\S*(?=\S{8,})(?=\S*[a-z])(?=\S*[A-Z])(?=\S*[\d])(?=\S*[\W])\S*$
$ = beginning of string 
\S* = any set of characters
(?=\S{8,}) = of at least length 8
(?=\S*[a-z]) = containing at least one lowercase letter
(?=\S*[A-Z]) = and at least one uppercase letter
(?=\S*[\d]) = and at least one number
(?=\S*[\W]) = and at least a special character (non-word characters)
$ = end of the string

**Comment by kotyy** [comment]
Sorry for the delay getting back. I think the issue is the leading `$`, which means end of string, not beginning. 

If you replace the initial `$` with `^`, `passwOrd1%` will pass the test.

Try `/^\S*(?=\S{8,})(?=\S*[a-z])(?=\S*[A-Z])(?=\S*[\d])(?=\S*[\W])\S*$/` and see if that works?
