### ISSUE TITLE
How do you get the validation error?

### ISSUE THREAD

**Issue by jz-wilson** [kotyy/craft-password-enforcer#3]
I am getting the normal craft errors when having some trying to register but I'm not sure how to get these errors.

This what we are currently using: 

```html
<label class="login-page_label" for="password">
  <input class="login-page_input" type="password" id="password" name="password">
{% if account is defined %}
  {{ errorList(account.getErrors('password')) }}
{% endif %}
  <span class="login-page_placeholder">Password</span>
</label>

```

**Comment by kotyy** [comment]
This plugin performs its actions after the password is validated by Craft, therefore if the password fails to meet Craft's password requirements, this plugin is not invoked.

Also, this plugin was only intended to work with Craft's password change fields and associates the error messages with an attribute called 'newPassword'. Changing you form field's name to match may work.
